In [44]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import random

In [56]:
df = pd.read_csv('WB_data.csv', encoding = 'unicode_escape', delimiter = '\t')
df.head()

                                                                                                                                                    Country Name\tCountry Code\tSeries Name\tSeries Code\t2000\t2001\t2002\t2003\t2004\t2005\t2006\t2007\t2008\t2009\t2010\t2011\t2012\t2013\t2014\t2015\t2016\t2017\t2018\t2019,,,
Afghanistan\tAFG\t"Adjusted net enrollment rate... SE.PRM.TENR          ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..                                               ..",,
Afghanistan\tAFG\t"Adjusted net enrollment rate... SE.PRM.TENR.FE       ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..                                                ..",
Afghanistan\tAFG\t"Adjusted net enrollment rate... SE.PRM.TENR.MA       ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..                                                ..",
Afghanistan\tAFG\tAdolescents out of school (% ... NaN                  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN                                                NaN
Afghanistan\tAFG\t"Adolescents out of school," ... SE.SEC.UNER.LO.FE.ZS ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..                                               ..",,

In [50]:
#read data
# the encoding is different so I had to use heading 0 and unicode escapte encoding to read it.
df = pd.read_csv('WB_data.csv',delimiter = '\t', encoding = 'unicode_escape', dtype={'Country Name':str, 'Country Code':str, 'Series Name':str, 'Series Code':str})

#replace the ".."s with NaNs for easier workflow
#df = df.replace("..", np.nan)

#and remove unnecessary Country Code and Series Code columns
#df = df.drop(['Country Code', 'Series Code'],axis = 1)

#display the first 5 rows
df.head()

                                                                                                                                                    Country Name\tCountry Code\tSeries Name\tSeries Code\t2000\t2001\t2002\t2003\t2004\t2005\t2006\t2007\t2008\t2009\t2010\t2011\t2012\t2013\t2014\t2015\t2016\t2017\t2018\t2019,,,
Afghanistan\tAFG\t"Adjusted net enrollment rate... SE.PRM.TENR          ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..                                               ..",,
Afghanistan\tAFG\t"Adjusted net enrollment rate... SE.PRM.TENR.FE       ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..                                                ..",
Afghanistan\tAFG\t"Adjusted net enrollment rate... SE.PRM.TENR.MA       ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..                                                ..",
Afghanistan\tAFG\tAdolescents out of school (% ... NaN                  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN                                                NaN
Afghanistan\tAFG\t"Adolescents out of school," ... SE.SEC.UNER.LO.FE.ZS ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..                                               ..",,

In [ ]:
df['Country Name'].unique()

#df.head()

In [5]:
df.dtypes

Country Name    object
Series Name     object
2000            object
2001            object
2002            object
2003            object
2004            object
2005            object
2006            object
2007            object
2008            object
2009            object
2010            object
2011            object
2012            object
2013            object
2014            object
2015            object
2016            object
2017            object
2018            object
2019            object
dtype: object

In [6]:
#name the colmuns so we can change the data type of the columns using a loop
Col_Names = list(df.columns)

for Col in Col_Names[2:]:
    df[Col] = pd.to_numeric(df[Col], errors = 'coerce')
for Col in Col_Names[:2]:
    df[Col] = df[Col].astype('str')


df.dtypes

Country Name     object
Series Name      object
2000            float64
2001            float64
2002            float64
2003            float64
2004            float64
2005            float64
2006            float64
2007            float64
2008            float64
2009            float64
2010            float64
2011            float64
2012            float64
2013            float64
2014            float64
2015            float64
2016            float64
2017            float64
2018            float64
2019            float64
dtype: object

In [28]:
df.groupby('Country Name')[['2000', '2001']].aggregate('mean')

                                  2000          2001
Country Name
Afghanistan               5.508816e+05  6.265931e+05
Albania                   5.239565e+04  5.533514e+04
Algeria                   5.383877e+05  5.962652e+05
American Samoa            1.799600e+03  2.465454e+03
Andorra                   1.035409e+03  1.237629e+03
Angola                    3.250014e+05  3.936896e+05
Antigua and Barbuda       2.698977e+03  3.587087e+03
Argentina                 6.140744e+05  6.204454e+05
Armenia                   6.079838e+04  6.064381e+04
Aruba                     1.766982e+03  2.053587e+03
Australia                 3.709199e+05  4.040448e+05
Austria                   1.375068e+05  1.566212e+05
Azerbaijan                1.453110e+05  1.559677e+05
Bahamas, The              6.799798e+03  8.257272e+03
Bahrain                   1.292828e+04  1.309773e+04
Bangladesh                2.074128e+06  2.490857e+06
Barbados                  4.676037e+03  5.128767e+03
Belarus                   1.758292e+05  1.948373e+05
Belgium                   1.798536e+05  2.071944e+05
Belize                    4.227616e+03  4.815705e+03
Benin                     1.151460e+05  1.254301e+05
Bermuda                   7.170653e+02  7.873203e+02
Bhutan                    1.104106e+04  1.282765e+04
Bolivia                   1.437836e+05  1.565464e+05
Bosnia and Herzegovina    8.069609e+04  8.851557e+04
Botswana                  2.716922e+04  3.163397e+04
Brazil                    3.612746e+06  3.212912e+06
British Virgin Islands    3.226825e+02  3.218759e+02
Brunei Darussalam         7.086074e+03  7.700127e+03
Bulgaria                  1.283143e+05  1.238498e+05
...                                ...           ...
Switzerland               1.199420e+05  1.323191e+05
Syrian Arab Republic      2.812878e+05  3.092531e+05
Tajikistan                9.926848e+04  1.231564e+05
Tanzania                  6.407733e+05  6.344082e+05
Thailand                  1.085797e+06  1.317559e+06
Timor-Leste               2.760801e+04  2.583143e+04
Togo                      8.495135e+04  1.045542e+05
Tonga                     2.172870e+03  2.056044e+03
Trinidad and Tobago       2.144488e+04  2.542372e+04
Tunisia                   1.545178e+05  1.758251e+05
Turkey                    1.164816e+06  1.341852e+06
Turkmenistan              9.706878e+04  1.189360e+05
Turks and Caicos Islands  4.172388e+02  4.166540e+02
Tuvalu                    1.815375e+02  1.575076e+02
Uganda                    5.027840e+05  5.309268e+05
Ukraine                   8.751623e+05  9.031669e+05
United Arab Emirates      6.455440e+04  7.846368e+04
United Kingdom            9.789715e+05  1.063349e+06
United States             4.665093e+06  5.523652e+06
Uruguay                   5.409216e+04  6.027620e+04
Uzbekistan                4.552082e+05  5.138133e+05
Vanuatu                   3.559879e+03  3.933018e+03
Venezuela, RB             4.266102e+05  4.488426e+05
Vietnam                   1.413791e+06  1.617195e+06
Virgin Islands (U.S.)     4.327127e+03  4.528964e+03
West Bank and Gaza        5.285535e+04  5.599858e+04
Yemen, Rep.               3.697314e+05  3.812931e+05
Zambia                    1.933711e+05  2.495150e+05
Zimbabwe                  2.553010e+05  2.744448e+05
nan                                NaN           NaN

[220 rows x 2 columns]

In [ ]:
#do some EDA here
#pick 4-5 indicators to compare between 3n countries, for core, semiperi and peri comparison

In [ ]:
#graph those